### ISSUE TITLE
pandas implementation no longer works

### ISSUE THREAD

**Issue by outs1der** [outs1der/minbar#8]
Here's the old text from `README.md` with suggested usage:

> ### pandas ###
> 
> [pandas](https://pandas.pydata.org/) is a data analysis library with many
> features. The Minbar databases can be loaded as pandas DataFrames:
> 
> ```
> #!python
> 
> import minbar.to_pandas
> mb = minbar.to_pandas.load_bursts() # Create a DataFrame with burst data
> mo = minbar.to_pandas.load_observations()
> ms = minbar.to_pandas.load_sources()
> df = mb.get_source('1636') # Select a source using part of its name
> df = mb.get_instrument('pca') # Select an instrument ('pca', 'wfc', or 'jemx')
> ```

**Comment by yveskini** [comment]
I got around the pandas' issue by first installing pandas in the conda environment, and then I proceeded to install minbar and other required packages.

**Comment by outs1der** [comment]
No this is just an issue with the `to_pandas` method, which throws an error:

```
>>> mb = minbar.to_pandas.load_bursts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Shared/burst/minbar/pyminbar/minbar/to_pandas.py", line 79, in load_bursts
    return _minbar2pandas()
  File "/Users/Shared/burst/minbar/pyminbar/minbar/to_pandas.py", line 70, in _minbar2pandas
    data = data.byteswap().newbyteorder('N') # Switch to native byteorder for pandas
AttributeError: 'Table' object has no attribute 'byteswap'
```

It should be possible to use `pandas` fine in other contexts
